import Vue from 'vue';
import '@swhy/sw-bw-ui/src/components/style/base.scss';
import { Button, NavBar, Modal, Block, Loadmore, Toast, Search, Empty, Loading, LazyLoader, InputItem, Cell, Numeric, Swipe, Tabs, Popup, Collapse, Picker, DatetimePicker, NumberInput, Amount, Radio, Icon, Agree, Divider, Checkbox, DropdownMenu, Switch, Progress } from '@swhy/sw-bw-ui';
Vue.use(Button);
Vue.use(NavBar);
Vue.use(Block);
Vue.use(Loadmore);
Vue.use(Modal);
Vue.use(Toast);
Vue.use(Search);
Vue.use(Empty);
Vue.use(Loading);
Vue.use(LazyLoader);
Vue.use(InputItem);
Vue.use(Cell);
Vue.use(Numeric);
Vue.use(Swipe);
Vue.use(Tabs);
Vue.use(Popup);
Vue.use(Collapse);
Vue.use(Picker);
Vue.use(DatetimePicker);
Vue.use(NumberInput);
Vue.use(Amount);
Vue.use(Radio);
Vue.use(Icon);
Vue.use(Agree);
Vue.use(Checkbox);
Vue.use(DropdownMenu);
Vue.use(Divider);
Vue.use(Switch);
Vue.use(Progress);
